### PR TITLE
Make error printing line uniform

### PR DESCRIPTION
**Pull request by whatnick**
Needed to patch this to work on Python 3.5

### CODE REVIEW

**Comment by whatnick** [comment]
Please merge for working Python 3.5 and 3.6 code.

**Comment by nicorellius** [comment]
What about using string formatting (`format(e)`) instead of concatenation?

**Comment by whatnick** [comment]
Sure just consistency and working code.

**Comment by nicorellius** [comment]
@whatnick Released new version to PyPI... Thanks for the PR.

**Pull request merged**
